# configs/config.yaml

data:
  raw_data_path: "data/raw/"

model:
  llm_name: "llava-llama3"
  embedding_model_name: "paraphrase-multilingual-MiniLM-L12-v2" # @https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  batch_size: 32

tokenizer:
  path: "tokenizers/punkt/portuguese.pickle"

prompts:
  template_file: "prompts/prompt_template.yml"

retrieval:
  collection_name: "juris"
  n_results: 10
